### ISSUE TITLE
How Do You install this?

### ISSUE THREAD

**Issue by ORCTreee** [jwoodruff40/advdupe2-tools#2]
How Does one Install the Code?

**Comment by jwoodruff40** [comment]
Just download the code, unzip it, and move to the add-ons folder

**Comment by ORCTreee** [comment]
Do i need to put it in my addons folder on my server to use it there or does it work Client side?

**Comment by jwoodruff40** [comment]
Believe it should work clientside as long as AD2 is loaded on the server. I've only actually tried in single player.
